# Generated by Django 4.2.1 on 2024-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacenamiento',
            field=models.CharField(default='', max_length=5),
        ),
    ]
